### ISSUE TITLE
Needed JSON sample data 

### ISSUE THREAD

**Issue by Pmacdon15** [Pmacdon15/final_project_web#13]
We will Need JSON files for All Programs, User Programs, All Courses, User Courses.

**Comment by Pmacdon15** [comment]
As discussed we should split students from users and courses available will be based on term.

**Comment by Pmacdon15** [comment]
I take it back to make it easy we should use a flag ... isAdmin as we are doing I think that's much easier. The only sample data we need now is user classes.

**Comment by manufflopes** [comment]
I update the users.data.js with some courses... if you guys could check

**Comment by Pmacdon15** [comment]
Where? Did yiu make a branch? What's its name? I'll check tomorrow ? Or are you going to make a pr?

**Comment by manufflopes** [comment]
I made a PR, and the name of the branch is users-data-json-and-login-feature
