### ISSUE TITLE
Needed Bow Valley label with white text

### ISSUE THREAD

**Issue by Pmacdon15** [Pmacdon15/final_project_web#16]
If somebody could find a Bow Valley College logo with white text and replace it in the app bar that would be wonderful.

**Comment by thiagolima19** [comment]
I found this BVC Logo https://cea.bowvalleycollege.ca/ Is this one that you wanted?

**Comment by Pmacdon15** [comment]
Can you create a component that uses the white logo and import it in to the navbar instead of the one we have? @thiagolima19
