### ISSUE TITLE
Add property to Navbar isAdmin

### ISSUE THREAD

**Issue by Pmacdon15** [Pmacdon15/final_project_web#35]
# Description
We should add a property to the nav bar called is admin and it should navigate to the admin portal if the user is an admin and a student if the user is a guest or student. We will have to change the route that's being navigated in the nav bar as well as some sort of function on login to send the user to admin-portal-all-programs/email.

# Todo
- Add property to nav bar
- Add property to nav bar Instances
- Add ternary or if statements to correctly navigate to the correct link

# Main spots to change:
## Spot 1:
NavBar.component.jsx:
![spot1](https://github.com/user-attachments/assets/4b8ddf59-b7c2-4c8b-994b-c8b43a21f1f8)

## Spot 2 :
LoginForm.component.jsx:
![spot2](https://github.com/user-attachments/assets/363a188f-c218-4f06-8a34-ec28ff01d020)

## Spot 3
- On every .page.jsx file where the nav bar is called.

**Comment by PALLAVIKHEDLE** [comment]
Hi @Pmacdon15,

I’ve reviewed the issue description, and it seems straightforward to resolve. I’d be happy to help fix it! Could you kindly assign this issue to me so I can get started?

**Comment by Pmacdon15** [comment]
As much as that's appreciated this is a project we are doing for school, So we will have to decline your assistance but I appreciate it.

**Comment by manufflopes** [comment]
https://github.com/Pmacdon15/final_project_web/pull/47
