### ISSUE TITLE
Remove option to log in as student or admin and just use one login or guest

### ISSUE THREAD

**Issue by Pmacdon15** [Pmacdon15/final_project_web#66]
We need to streamline the login form to just allow either login or use guest no need to differentiate between student and admin because logging in as an admin already redirects regardless of what screen is used.

**Comment by thiagolima19** [comment]
I think we can do that after this phase! or keep it as is because it is working fine!

**Comment by thiagolima19** [comment]
I made some changes, and this new PR will handle this functionality.
